services:  
  postgres-db:
    hostname: postgres-db
    ports:
      - "5432:5432"
    image: postgres:alpine
    environment:
      POSTGRES_DB: workout_app_db
      POSTGRES_USER: damcio
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - database:/data/postgres
    restart: always 


volumes:
  database: